#!/usr/bin/python
# -*- coding: UTF-8 -*-
class Solution(object):
    def connectMysql(self):
        import MySQLdb
        # 打开数据库连接
        """
        地址:10.141.208.45
        用户名:root
        密码:hadoop
        数据库:bridge
        """
        db = MySQLdb.connect("10.141.208.45","root","hadoop","bridge")
        # 使用cursor()方法获取操作游标
        cursor = db.cursor()
        # 使用execute方法执行SQL语句
        sql="SELECT code , frequence from channel_pra where nodetype = 1"
        sql2="SELECT count(*) as code from channel_pra where nodetype = 1"
        cursor.execute(sql)
        data1 = cursor.fetchall()
        cursor.execute(sql2)
        # 使用 fetchone() 方法获取一条数据库。
        data = cursor.fetchall()
        print "len:%s "%(len(data1))
        print data1
        # 关闭数据库连接
        cursor.close()
        db.close()



if __name__=="__main__":
    c=Solution()
    b=c.connectMysql()
